### VS code rest client test tool 

@host = http://localhost:8000

####################
### GetADS 
####################


### Wrong method
get {{host}}/getads 

### Without params 
post {{host}}/getads/ 
Content-Type: application/json

[]

### Working
post {{host}}/getads/ 
Content-Type: application/json

{
  "username": "aviv"
}


####################
### Impression 
####################

###  Wrong method
get {{host}}/impression 


### User not found 
post {{host}}/impression/ 
Content-Type: application/json

{
  "username": "asdasdddadas"
}

### Working
post {{host}}/impression/ 
Content-Type: application/json

{
  "username": "aviv"
}

####################
### GetStats
####################


### User not found 
get  {{host}}/getstats/aviv 


### Working
get  {{host}}/getstats/aaaaa 


####################
### All
####################

get  {{host}}/all